id: audit_acls_folders_configure
title: "Configure Audit Log Folder to Not Contain Access Control Lists"
discussion: |
  The audit log folder _MUST_ not contain access control lists (ACLs).

  Audit logs contain sensitive data about the system and users. This rule ensures that the audit service is configured to create log folders that are readable and writable only by system administrators in order to prevent normal users from reading audit logs.
check: |
  /bin/ls -lde $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}") | /usr/bin/awk "{print $1}" | /usr/bin/grep -c ":"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /bin/chmod -N $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}")
  ----
references:
  cce:
    - CCE-85252-5
  cci:
    - CCI-000162
  800-53r4:
    - AU-9
  srg:
    - SRG-OS-000057-GPOS-00027
  disa_stig:
    - APPL-11-000031
  800-171r2:
    - 3.3.8
macOS:
  - "11.0"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info:
