id: audit_files_group_configure
title: "Configure Audit Log Files Group to Wheel"
discussion: |
  Audit log files _MUST_ have the group set to wheel.

  The audit service _MUST_ be configured to create log files with the correct group ownership to prevent normal users from reading audit logs. 

  Audit logs contain sensitive data about the system and users. If log files are set to be readable and writable only by system administrators, the risk is mitigated.
check: |
  /bin/ls -n $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}") | /usr/bin/awk "{s+=$4} END {print s}"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/bin/chgrp -R wheel $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}")/*
  ----
references:
  cce:
    - CCE-85258-2
  cci:
    - CCI-000162
  800-53r4:
    - AU-9
  srg:
    - SRG-OS-000057-GPOS-00027
  disa_stig:
    - APPL-11-001014
  800-171r2:
    - 3.3.8
macOS:
  - "11.0"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info:
