id: audit_folder_group_configure
title: "Configure Audit Log Folders Group to Wheel"
discussion: |
  Audit log files _MUST_ have the group set to wheel.

  The audit service _MUST_ be configured to create log files with the correct group ownership to prevent normal users from reading audit logs. 

  Audit logs contain sensitive data about the system and users. If log files are set to be readable and writable only by system administrators, the risk is mitigated.
check: |
  /bin/ls -dn $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}") | /usr/bin/awk "{print $4}"
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/bin/chgrp wheel $(/usr/bin/awk -F : "/^dir/{print $2}" /etc/security/audit_control)
  ----
references:
  cce:
    - CCE-85268-1
  cci:
    - CCI-000162
  800-53r4:
    - AU-9
  srg:
    - SRG-OS-000033-GPOS-00014
  disa_stig:
    - APPL-11-001015
  800-171r2:
    - 3.3.8
macOS:
  - "11.0"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info:
