id: audit_files_mode_configure
title: "Configure Audit Log Files to Mode 440 or Less Permissive"
discussion: |
  The audit service _MUST_ be configured to create log files that are readable only by the root user and group wheel. To achieve this, audit log files _MUST_ be configured to mode 440 or less permissive; thereby preventing normal users from reading, modifying or deleting audit logs. 
check: |
  /bin/ls -l $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}") | /usr/bin/awk "!/-r--r-----|current|total/{print $1}" | /usr/bin/wc -l | /usr/bin/tr -d " "
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /bin/chmod 440 $(/usr/bin/grep "^dir" /etc/security/audit_control | /usr/bin/awk -F: "{print $2}")/*
  ----
references:
  cce:
    - CCE-85259-0
  cci: 
    - CCI-000162
  800-53r4: 
    - AU-9
  srg: 
    - SRG-OS-000057-GPOS-00027
  disa_stig: 
    - APPL-11-001016
  800-171r2:
    - 3.3.8
macOS:
  - "11.0"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - stig
severity: "medium"
mobileconfig: false
mobileconfig_info:
